import styled from 'styled-components';

import Head from 'next/head';

import Leaderboard from '../components/Leaderboard';
import Matches from '../components/Matches';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Section>
          <Leaderboard />
          <Matches />
        </Section>
      </Main>
    </div>
  );
}

const Main = styled.div`
  margin: 0 auto;
  max-width: 1010px;
  min-width: 320px;
`;

const Section = styled.section`
  display: flex;
  flex-direction: column;
  @media (min-width: 992px) {
    flex-direction: row;
  }
`;
